### PR TITLE
fix(index): fix PLATFORM.eachModule for SystemJS@0.20.x

### LINKED ISSUE #40: PLATFORM.eachModule is broken for SystemJS >= 0.20.0
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
JSPM 0.17.0-beta.40

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Depends on [System._loader](https://github.com/aurelia/loader-default/blob/a4607b97bfc2016e6feced5c04eb8259504b2efe/src/index.js#L179)
**Expected/desired behavior:**

* **What is the expected behavior?**
   
* **What is the motivation / use case for changing the behavior?**
`System._loader` has been [deprecated](https://github.com/systemjs/systemjs/blob/bde23996904743d6fe3ecaf75c196f1e5ca2c713/src/systemjs-loader.js#L45) - [commit](https://github.com/systemjs/systemjs/commit/a2913206d45eaabafda289d48f06b42b9e5256dd), and now is just an empty object. 
For SystemJS =>0.20.x [Origin.get(ClassOfInterest)](https://github.com/aurelia/dialog/blob/b216b0597892293f4949b1f22701c24c8d8040f7/src/dialog-service.js#L111) returns `{ moduleId: undefined, moduleMember: undefined }` - aurelia/dialog#257

### PR DESCRIPTION
**Pull request by StrahilKazlachev**
fix #40

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -176,6 +176,16 @@ if (!PLATFORM.global.System || !PLATFORM.global.System.import) {
   };
 } else {
   PLATFORM.eachModule = function(callback) {
+    if (System.registry) { // SystemJS >= 0.20.x
+      for (let [k, m] of System.registry.entries()) {
```
Comment (StrahilKazlachev) [inline src/index.js]: Form the [registry API](https://github.com/systemjs/systemjs/blob/ec39166a8e89a0fe3048cddc63d45c5580deffea/docs/system-api.md#systemjsregistry) I do not see how to avoid the iterable. But could switch from `for...of` to `Array.from`+`for`.
